services:
  http-server-projeto-korp:
    image: http-server-projeto-korp:1.0
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8080"
    networks:
      - projeto-korp-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - http-server-projeto-korp
    networks:
      - projeto-korp-network

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - http-server-projeto-korp
    networks:
      - projeto-korp-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    depends_on:
      - prometheus
    networks:
      - projeto-korp-network

networks:
  projeto-korp-network:
    external: true

volumes:
  grafana-data: